/**
 * U-Calm Aviation — brand imagery manifest.
 *
 * 162 slots across 13 sections — generated from brand-assets/scripts/prompts.py
 * (see Aviation imagery library, single source of truth for Gemini 3.1 Flash
 * Image generation). Each entry points at a real generated jpg under
 * /public/brand/<section>/<filename>. Until those photographs are generated
 * and dropped into /public/brand/, the <BrandImage> component renders the
 * gradient horizon placeholder for every slot (controlled by IMAGERY_READY
 * below).
 *
 * Components reference slots via the typed export constants below
 * (PAGE_HEROES, THREE_CITIES, HOME_EDITORIAL, SERVICES_SCENES, ABOUT_SCENES,
 * CONTACT_EDITORIAL, SEASONAL_BANK). Never import BRAND_IMAGES directly or
 * hard-code filenames.
 *
 * Section structure (13 sections, IDs 1-162):
 *   §1  Brand Heroes and Openers           (10) — IDs 1-10
 *   §2  London — Residence and Corridor    (14) — IDs 11-24
 *   §3  Lugano and Ticino                  (10) — IDs 25-34
 *   §4  Gstaad, St Moritz, Alpine Quiet    (14) — IDs 35-48
 *   §5  Monaco and the Côte d'Azur         (10) — IDs 49-58
 *   §6  Mediterranean Islands              (14) — IDs 59-72
 *   §7  Provence and Countryside           (10) — IDs 73-82
 *   §8  Caribbean and Transatlantic         (8) — IDs 83-90
 *   §9  Domestic Interiors                 (15) — IDs 91-105
 *   §10 Cabin Stills                       (13) — IDs 106-118
 *   §11 Hands-only Vignettes               (14) — IDs 119-132
 *   §12 Textures, Ambient, Arrivals        (18) — IDs 133-150
 *   §13 Milan — English-speaker city       (12) — IDs 151-162
 */

export type BrandAspect = "4:5" | "16:9" | "1:1" | "3:4" | "21:9";

export type BrandImage = {
  id: number;
  section: string;
  slotKey: string;
  filename: string;
  title: string;
  aspect: BrandAspect;
  src: string;
  alt: string;
  enabled: boolean;
};

export const BRAND_IMAGES: readonly BrandImage[] = [
  // ─── §1 Brand Heroes and Openers ─────────────────────────────
  {
    id: 1,
    section: "01-brand-heroes",
    slotKey: "hero-home-to-air",
    filename: "hero-home-to-air.jpg",
    title: "Home to air, morning",
    aspect: "16:9",
    src: "/brand/01-brand-heroes/hero-home-to-air.jpg",
    alt: "Home to air, morning — Brand Heroes and Openers",
    enabled: true,
  },
  {
    id: 2,
    section: "01-brand-heroes",
    slotKey: "hero-quiet-threshold",
    filename: "hero-quiet-threshold.jpg",
    title: "Quiet threshold",
    aspect: "16:9",
    src: "/brand/01-brand-heroes/hero-quiet-threshold.jpg",
    alt: "Quiet threshold — Brand Heroes and Openers",
    enabled: true,
  },
  {
    id: 3,
    section: "01-brand-heroes",
    slotKey: "hero-aviation-arranged",
    filename: "hero-aviation-arranged.jpg",
    title: "Aviation, arranged",
    aspect: "21:9",
    src: "/brand/01-brand-heroes/hero-aviation-arranged.jpg",
    alt: "Aviation, arranged — Brand Heroes and Openers",
    enabled: true,
  },
  {
    id: 4,
    section: "01-brand-heroes",
    slotKey: "hero-lake-lugano-dawn",
    filename: "hero-lake-lugano-dawn.jpg",
    title: "Lake Lugano, first light",
    aspect: "16:9",
    src: "/brand/01-brand-heroes/hero-lake-lugano-dawn.jpg",
    alt: "Lake Lugano, first light — Brand Heroes and Openers",
    enabled: true,
  },
  {
    id: 5,
    section: "01-brand-heroes",
    slotKey: "hero-gstaad-chalet",
    filename: "hero-gstaad-chalet.jpg",
    title: "Chalet morning, Gstaad",
    aspect: "4:5",
    src: "/brand/01-brand-heroes/hero-gstaad-chalet.jpg",
    alt: "Chalet morning, Gstaad — Brand Heroes and Openers",
    enabled: true,
  },
  {
    id: 6,
    section: "01-brand-heroes",
    slotKey: "hero-monaco-balcony",
    filename: "hero-monaco-balcony.jpg",
    title: "Monaco balcony, 17:30",
    aspect: "16:9",
    src: "/brand/01-brand-heroes/hero-monaco-balcony.jpg",
    alt: "Monaco balcony, 17:30 — Brand Heroes and Openers",
    enabled: true,
  },
  {
    id: 7,
    section: "01-brand-heroes",
    slotKey: "hero-mykonos-threshold",
    filename: "hero-mykonos-threshold.jpg",
    title: "Mykonos, white and teal",
    aspect: "4:5",
    src: "/brand/01-brand-heroes/hero-mykonos-threshold.jpg",
    alt: "Mykonos, white and teal — Brand Heroes and Openers",
    enabled: true,
  },
  {
    id: 8,
    section: "01-brand-heroes",
    slotKey: "hero-cabin-window-cloud",
    filename: "hero-cabin-window-cloud.jpg",
    title: "Cabin window, soft cloud",
    aspect: "4:5",
    src: "/brand/01-brand-heroes/hero-cabin-window-cloud.jpg",
    alt: "Cabin window, soft cloud — Brand Heroes and Openers",
    enabled: true,
  },
  {
    id: 9,
    section: "01-brand-heroes",
    slotKey: "hero-mustique-hammock",
    filename: "hero-mustique-hammock.jpg",
    title: "Mustique veranda",
    aspect: "16:9",
    src: "/brand/01-brand-heroes/hero-mustique-hammock.jpg",
    alt: "Mustique veranda — Brand Heroes and Openers",
    enabled: true,
  },
  {
    id: 10,
    section: "01-brand-heroes",
    slotKey: "hero-navigation-detail",
    filename: "hero-navigation-detail.jpg",
    title: "Navigation, abstracted",
    aspect: "1:1",
    src: "/brand/01-brand-heroes/hero-navigation-detail.jpg",
    alt: "Navigation, abstracted — Brand Heroes and Openers",
    enabled: true,
  },
  // ─── §2 London — Residence and Corridor ─────────────────────────────
  {
    id: 11,
    section: "02-london",
    slotKey: "london-knightsbridge-hall",
    filename: "london-knightsbridge-hall.jpg",
    title: "Knightsbridge hall",
    aspect: "4:5",
    src: "/brand/02-london/london-knightsbridge-hall.jpg",
    alt: "Knightsbridge hall — London — Residence and Corridor",
    enabled: true,
  },
  {
    id: 12,
    section: "02-london",
    slotKey: "london-mews-threshold",
    filename: "london-mews-threshold.jpg",
    title: "Mews doorway, rain",
    aspect: "16:9",
    src: "/brand/02-london/london-mews-threshold.jpg",
    alt: "Mews doorway, rain — London — Residence and Corridor",
    enabled: true,
  },
  {
    id: 13,
    section: "02-london",
    slotKey: "london-study-desk",
    filename: "london-study-desk.jpg",
    title: "Study desk, slim laptop",
    aspect: "1:1",
    src: "/brand/02-london/london-study-desk.jpg",
    alt: "Study desk, slim laptop — London — Residence and Corridor",
    enabled: true,
  },
  {
    id: 14,
    section: "02-london",
    slotKey: "london-dressing-room",
    filename: "london-dressing-room.jpg",
    title: "Dressing room before departure",
    aspect: "4:5",
    src: "/brand/02-london/london-dressing-room.jpg",
    alt: "Dressing room before departure — London — Residence and Corridor",
    enabled: true,
  },
  {
    id: 15,
    section: "02-london",
    slotKey: "london-breakfast-tray",
    filename: "london-breakfast-tray.jpg",
    title: "Breakfast tray, quiet kitchen",
    aspect: "3:4",
    src: "/brand/02-london/london-breakfast-tray.jpg",
    alt: "Breakfast tray, quiet kitchen — London — Residence and Corridor",
    enabled: true,
  },
  {
    id: 16,
    section: "02-london",
    slotKey: "london-hallway-holdall",
    filename: "london-hallway-holdall.jpg",
    title: "Holdall by the door",
    aspect: "1:1",
    src: "/brand/02-london/london-hallway-holdall.jpg",
    alt: "Holdall by the door — London — Residence and Corridor",
    enabled: true,
  },
  {
    id: 17,
    section: "02-london",
    slotKey: "london-car-kerb",
    filename: "london-car-kerb.jpg",
    title: "Car at the kerb, Westbourne",
    aspect: "16:9",
    src: "/brand/02-london/london-car-kerb.jpg",
    alt: "Car at the kerb, Westbourne — London — Residence and Corridor",
    enabled: true,
  },
  {
    id: 18,
    section: "02-london",
    slotKey: "london-rain-glass",
    filename: "london-rain-glass.jpg",
    title: "Rain on sash glass",
    aspect: "1:1",
    src: "/brand/02-london/london-rain-glass.jpg",
    alt: "Rain on sash glass — London — Residence and Corridor",
    enabled: true,
  },
  {
    id: 19,
    section: "02-london",
    slotKey: "london-farnborough-apron",
    filename: "london-farnborough-apron.jpg",
    title: "Farnborough, first light",
    aspect: "21:9",
    src: "/brand/02-london/london-farnborough-apron.jpg",
    alt: "Farnborough, first light — London — Residence and Corridor",
    enabled: true,
  },
  {
    id: 20,
    section: "02-london",
    slotKey: "london-biggin-gate",
    filename: "london-biggin-gate.jpg",
    title: "Quiet gatehouse, Biggin Hill",
    aspect: "16:9",
    src: "/brand/02-london/london-biggin-gate.jpg",
    alt: "Quiet gatehouse, Biggin Hill — London — Residence and Corridor",
    enabled: true,
  },
  {
    id: 21,
    section: "02-london",
    slotKey: "london-member-hallway-candle",
    filename: "london-member-hallway-candle.jpg",
    title: "Hallway, candlelight",
    aspect: "4:5",
    src: "/brand/02-london/london-member-hallway-candle.jpg",
    alt: "Hallway, candlelight — London — Residence and Corridor",
    enabled: true,
  },
  {
    id: 22,
    section: "02-london",
    slotKey: "london-evening-return",
    filename: "london-evening-return.jpg",
    title: "Evening return, threshold",
    aspect: "16:9",
    src: "/brand/02-london/london-evening-return.jpg",
    alt: "Evening return, threshold — London — Residence and Corridor",
    enabled: true,
  },
  {
    id: 23,
    section: "02-london",
    slotKey: "london-garden-window",
    filename: "london-garden-window.jpg",
    title: "Garden window, cloud-morning",
    aspect: "4:5",
    src: "/brand/02-london/london-garden-window.jpg",
    alt: "Garden window, cloud-morning — London — Residence and Corridor",
    enabled: true,
  },
  {
    id: 24,
    section: "02-london",
    slotKey: "london-stairwell",
    filename: "london-stairwell.jpg",
    title: "Stairwell, afternoon",
    aspect: "3:4",
    src: "/brand/02-london/london-stairwell.jpg",
    alt: "Stairwell, afternoon — London — Residence and Corridor",
    enabled: true,
  },
  // ─── §3 Lugano and Ticino — Lakeside Quiet ─────────────────────────────
  {
    id: 25,
    section: "03-lugano-ticino",
    slotKey: "lugano-villa-terrace-dawn",
    filename: "lugano-villa-terrace-dawn.jpg",
    title: "Villa terrace, 06:45",
    aspect: "16:9",
    src: "/brand/03-lugano-ticino/lugano-villa-terrace-dawn.jpg",
    alt: "Villa terrace, 06:45 — Lugano and Ticino — Lakeside Quiet",
    enabled: true,
  },
  {
    id: 26,
    section: "03-lugano-ticino",
    slotKey: "lugano-palazzo-doorway",
    filename: "lugano-palazzo-doorway.jpg",
    title: "Palazzo doorway, Lugano",
    aspect: "3:4",
    src: "/brand/03-lugano-ticino/lugano-palazzo-doorway.jpg",
    alt: "Palazzo doorway, Lugano — Lugano and Ticino — Lakeside Quiet",
    enabled: true,
  },
  {
    id: 27,
    section: "03-lugano-ticino",
    slotKey: "lugano-lake-jetty",
    filename: "lugano-lake-jetty.jpg",
    title: "Lake jetty, morning mist",
    aspect: "21:9",
    src: "/brand/03-lugano-ticino/lugano-lake-jetty.jpg",
    alt: "Lake jetty, morning mist — Lugano and Ticino — Lakeside Quiet",
    enabled: true,
  },
  {
    id: 28,
    section: "03-lugano-ticino",
    slotKey: "lugano-kitchen-porcelain",
    filename: "lugano-kitchen-porcelain.jpg",
    title: "Kitchen, porcelain and stone",
    aspect: "4:5",
    src: "/brand/03-lugano-ticino/lugano-kitchen-porcelain.jpg",
    alt: "Kitchen, porcelain and stone — Lugano and Ticino — Lakeside Quiet",
    enabled: true,
  },
  {
    id: 29,
    section: "03-lugano-ticino",
    slotKey: "lugano-gandria-alley",
    filename: "lugano-gandria-alley.jpg",
    title: "Gandria alley",
    aspect: "4:5",
    src: "/brand/03-lugano-ticino/lugano-gandria-alley.jpg",
    alt: "Gandria alley — Lugano and Ticino — Lakeside Quiet",
    enabled: true,
  },
  {
    id: 30,
    section: "03-lugano-ticino",
    slotKey: "lugano-mendrisio-vineyard",
    filename: "lugano-mendrisio-vineyard.jpg",
    title: "Mendrisiotto vineyard",
    aspect: "16:9",
    src: "/brand/03-lugano-ticino/lugano-mendrisio-vineyard.jpg",
    alt: "Mendrisiotto vineyard — Lugano and Ticino — Lakeside Quiet",
    enabled: true,
  },
  {
    id: 31,
    section: "03-lugano-ticino",
    slotKey: "lugano-interior-library",
    filename: "lugano-interior-library.jpg",
    title: "Library interior, Bellinzona",
    aspect: "4:5",
    src: "/brand/03-lugano-ticino/lugano-interior-library.jpg",
    alt: "Library interior, Bellinzona — Lugano and Ticino — Lakeside Quiet",
    enabled: true,
  },
  {
    id: 32,
    section: "03-lugano-ticino",
    slotKey: "lugano-boat-still",
    filename: "lugano-boat-still.jpg",
    title: "Wooden launch, stillness",
    aspect: "16:9",
    src: "/brand/03-lugano-ticino/lugano-boat-still.jpg",
    alt: "Wooden launch, stillness — Lugano and Ticino — Lakeside Quiet",
    enabled: true,
  },
  {
    id: 33,
    section: "03-lugano-ticino",
    slotKey: "lugano-alpine-shoulder",
    filename: "lugano-alpine-shoulder.jpg",
    title: "Crossing shoulder, wool cuff",
    aspect: "1:1",
    src: "/brand/03-lugano-ticino/lugano-alpine-shoulder.jpg",
    alt: "Crossing shoulder, wool cuff — Lugano and Ticino — Lakeside Quiet",
    enabled: true,
  },
  {
    id: 34,
    section: "03-lugano-ticino",
    slotKey: "lugano-church-bell",
    filename: "lugano-church-bell.jpg",
    title: "Morriello campanile, 06:30",
    aspect: "3:4",
    src: "/brand/03-lugano-ticino/lugano-church-bell.jpg",
    alt: "Morriello campanile, 06:30 — Lugano and Ticino — Lakeside Quiet",
    enabled: true,
  },
  // ─── §4 Gstaad, St Moritz and Alpine Quiet ─────────────────────────────
  {
    id: 35,
    section: "04-gstaad-alpine",
    slotKey: "gstaad-chalet-dawn",
    filename: "gstaad-chalet-dawn.jpg",
    title: "Chalet bedroom, first light",
    aspect: "4:5",
    src: "/brand/04-gstaad-alpine/gstaad-chalet-dawn.jpg",
    alt: "Chalet bedroom, first light — Gstaad, St Moritz and Alpine Quiet",
    enabled: true,
  },
  {
    id: 36,
    section: "04-gstaad-alpine",
    slotKey: "gstaad-fireplace",
    filename: "gstaad-fireplace.jpg",
    title: "Fireplace, evening",
    aspect: "16:9",
    src: "/brand/04-gstaad-alpine/gstaad-fireplace.jpg",
    alt: "Fireplace, evening — Gstaad, St Moritz and Alpine Quiet",
    enabled: true,
  },
  {
    id: 37,
    section: "04-gstaad-alpine",
    slotKey: "gstaad-window-snow",
    filename: "gstaad-window-snow.jpg",
    title: "Window snow, still morning",
    aspect: "3:4",
    src: "/brand/04-gstaad-alpine/gstaad-window-snow.jpg",
    alt: "Window snow, still morning — Gstaad, St Moritz and Alpine Quiet",
    enabled: true,
  },
  {
    id: 38,
    section: "04-gstaad-alpine",
    slotKey: "gstaad-ski-still",
    filename: "gstaad-ski-still.jpg",
    title: "Skis by the door",
    aspect: "4:5",
    src: "/brand/04-gstaad-alpine/gstaad-ski-still.jpg",
    alt: "Skis by the door — Gstaad, St Moritz and Alpine Quiet",
    enabled: true,
  },
  {
    id: 39,
    section: "04-gstaad-alpine",
    slotKey: "gstaad-alpine-pass",
    filename: "gstaad-alpine-pass.jpg",
    title: "Alpine pass, early sun",
    aspect: "21:9",
    src: "/brand/04-gstaad-alpine/gstaad-alpine-pass.jpg",
    alt: "Alpine pass, early sun — Gstaad, St Moritz and Alpine Quiet",
    enabled: true,
  },
  {
    id: 40,
    section: "04-gstaad-alpine",
    slotKey: "gstaad-cashmere-throw",
    filename: "gstaad-cashmere-throw.jpg",
    title: "Cashmere folded",
    aspect: "1:1",
    src: "/brand/04-gstaad-alpine/gstaad-cashmere-throw.jpg",
    alt: "Cashmere folded — Gstaad, St Moritz and Alpine Quiet",
    enabled: true,
  },
  {
    id: 41,
    section: "04-gstaad-alpine",
    slotKey: "gstaad-village-path",
    filename: "gstaad-village-path.jpg",
    title: "Village path, morning",
    aspect: "16:9",
    src: "/brand/04-gstaad-alpine/gstaad-village-path.jpg",
    alt: "Village path, morning — Gstaad, St Moritz and Alpine Quiet",
    enabled: true,
  },
  {
    id: 42,
    section: "04-gstaad-alpine",
    slotKey: "gstaad-interior-library",
    filename: "gstaad-interior-library.jpg",
    title: "Chalet library",
    aspect: "4:5",
    src: "/brand/04-gstaad-alpine/gstaad-interior-library.jpg",
    alt: "Chalet library — Gstaad, St Moritz and Alpine Quiet",
    enabled: true,
  },
  {
    id: 43,
    section: "04-gstaad-alpine",
    slotKey: "stmoritz-lake-afternoon",
    filename: "stmoritz-lake-afternoon.jpg",
    title: "St Moritz lake, 16:00",
    aspect: "21:9",
    src: "/brand/04-gstaad-alpine/stmoritz-lake-afternoon.jpg",
    alt: "St Moritz lake, 16:00 — Gstaad, St Moritz and Alpine Quiet",
    enabled: true,
  },
  {
    id: 44,
    section: "04-gstaad-alpine",
    slotKey: "stmoritz-lobby-window",
    filename: "stmoritz-lobby-window.jpg",
    title: "Engadin window seat",
    aspect: "4:5",
    src: "/brand/04-gstaad-alpine/stmoritz-lobby-window.jpg",
    alt: "Engadin window seat — Gstaad, St Moritz and Alpine Quiet",
    enabled: false, // Disabled 2026-05-05 — Michael: "Really weird see through room, no thanks"
  },
  {
    id: 45,
    section: "04-gstaad-alpine",
    slotKey: "alpine-morning-coffee",
    filename: "alpine-morning-coffee.jpg",
    title: "Morning coffee, balcony",
    aspect: "1:1",
    src: "/brand/04-gstaad-alpine/alpine-morning-coffee.jpg",
    alt: "Morning coffee, balcony — Gstaad, St Moritz and Alpine Quiet",
    enabled: true,
  },
  {
    id: 46,
    section: "04-gstaad-alpine",
    slotKey: "alpine-skihold-macro",
    filename: "alpine-skihold-macro.jpg",
    title: "Ski bag, threshold",
    aspect: "16:9",
    src: "/brand/04-gstaad-alpine/alpine-skihold-macro.jpg",
    alt: "Ski bag, threshold — Gstaad, St Moritz and Alpine Quiet",
    enabled: true,
  },
  {
    id: 47,
    section: "04-gstaad-alpine",
    slotKey: "alpine-pine-detail",
    filename: "alpine-pine-detail.jpg",
    title: "Pine needles, close",
    aspect: "1:1",
    src: "/brand/04-gstaad-alpine/alpine-pine-detail.jpg",
    alt: "Pine needles, close — Gstaad, St Moritz and Alpine Quiet",
    enabled: true,
  },
  {
    id: 48,
    section: "04-gstaad-alpine",
    slotKey: "alpine-dusk-larch",
    filename: "alpine-dusk-larch.jpg",
    title: "Larch at dusk",
    aspect: "3:4",
    src: "/brand/04-gstaad-alpine/alpine-dusk-larch.jpg",
    alt: "Larch at dusk — Gstaad, St Moritz and Alpine Quiet",
    enabled: true,
  },
  // ─── §5 Monaco and the Côte d'Azur ─────────────────────────────
  {
    id: 49,
    section: "05-monaco-cote-dazur",
    slotKey: "monaco-balcony-17h",
    filename: "monaco-balcony-17h.jpg",
    title: "Monte Carlo balcony",
    aspect: "16:9",
    src: "/brand/05-monaco-cote-dazur/monaco-balcony-17h.jpg",
    alt: "Monte Carlo balcony — Monaco and the Côte d\'Azur",
    enabled: true,
  },
  {
    id: 50,
    section: "05-monaco-cote-dazur",
    slotKey: "capferrat-terrace",
    filename: "capferrat-terrace.jpg",
    title: "Cap Ferrat terrace",
    aspect: "4:5",
    src: "/brand/05-monaco-cote-dazur/capferrat-terrace.jpg",
    alt: "Cap Ferrat terrace — Monaco and the Côte d\'Azur",
    enabled: true,
  },
  {
    id: 51,
    section: "05-monaco-cote-dazur",
    slotKey: "monaco-study-lamplit",
    filename: "monaco-study-lamplit.jpg",
    title: "Private study, lamplit",
    aspect: "1:1",
    src: "/brand/05-monaco-cote-dazur/monaco-study-lamplit.jpg",
    alt: "Private study, lamplit — Monaco and the Côte d\'Azur",
    enabled: true,
  },
  {
    id: 52,
    section: "05-monaco-cote-dazur",
    slotKey: "monaco-threshold",
    filename: "monaco-threshold.jpg",
    title: "Monte Carlo doorstep",
    aspect: "4:5",
    src: "/brand/05-monaco-cote-dazur/monaco-threshold.jpg",
    alt: "Monte Carlo doorstep — Monaco and the Côte d\'Azur",
    enabled: true,
  },
  {
    id: 53,
    section: "05-monaco-cote-dazur",
    slotKey: "cotedazur-cape",
    filename: "cotedazur-cape.jpg",
    title: "Cape, late afternoon",
    aspect: "3:4",
    src: "/brand/05-monaco-cote-dazur/cotedazur-cape.jpg",
    alt: "Cape, late afternoon — Monaco and the Côte d\'Azur",
    enabled: true,
  },
  {
    id: 54,
    section: "05-monaco-cote-dazur",
    slotKey: "monaco-car-kerb",
    filename: "monaco-car-kerb.jpg",
    title: "Car at the curb, harbour road",
    aspect: "16:9",
    src: "/brand/05-monaco-cote-dazur/monaco-car-kerb.jpg",
    alt: "Car at the curb, harbour road — Monaco and the Côte d\'Azur",
    enabled: true,
  },
  {
    id: 55,
    section: "05-monaco-cote-dazur",
    slotKey: "coastal-breakfast-tray",
    filename: "coastal-breakfast-tray.jpg",
    title: "Coastal breakfast tray",
    aspect: "3:4",
    src: "/brand/05-monaco-cote-dazur/coastal-breakfast-tray.jpg",
    alt: "Coastal breakfast tray — Monaco and the Côte d\'Azur",
    enabled: true,
  },
  {
    id: 56,
    section: "05-monaco-cote-dazur",
    slotKey: "monaco-harbour-mist",
    filename: "monaco-harbour-mist.jpg",
    title: "Harbour mist, early",
    aspect: "21:9",
    src: "/brand/05-monaco-cote-dazur/monaco-harbour-mist.jpg",
    alt: "Harbour mist, early — Monaco and the Côte d\'Azur",
    enabled: true,
  },
  {
    id: 57,
    section: "05-monaco-cote-dazur",
    slotKey: "menton-lemon-detail",
    filename: "menton-lemon-detail.jpg",
    title: "Menton lemon, restrained",
    aspect: "1:1",
    src: "/brand/05-monaco-cote-dazur/menton-lemon-detail.jpg",
    alt: "Menton lemon, restrained — Monaco and the Côte d\'Azur",
    enabled: true,
  },
  {
    id: 58,
    section: "05-monaco-cote-dazur",
    slotKey: "nice-promenade",
    filename: "nice-promenade.jpg",
    title: "Promenade, overcast",
    aspect: "16:9",
    src: "/brand/05-monaco-cote-dazur/nice-promenade.jpg",
    alt: "Promenade, overcast — Monaco and the Côte d\'Azur",
    enabled: true,
  },
  // ─── §6 Ibiza, Mykonos, Mustique — Islands ─────────────────────────────
  {
    id: 59,
    section: "06-mediterranean-islands",
    slotKey: "ibiza-cala-stone-house",
    filename: "ibiza-cala-stone-house.jpg",
    title: "Ibiza finca, 17:30",
    aspect: "4:5",
    src: "/brand/06-mediterranean-islands/ibiza-cala-stone-house.jpg",
    alt: "Ibiza finca, 17:30 — Ibiza, Mykonos, Mustique — Islands",
    enabled: true,
  },
  {
    id: 60,
    section: "06-mediterranean-islands",
    slotKey: "mykonos-threshold",
    filename: "mykonos-threshold.jpg",
    title: "Mykonos threshold, open door",
    aspect: "4:5",
    src: "/brand/06-mediterranean-islands/mykonos-threshold.jpg",
    alt: "Mykonos threshold, open door — Ibiza, Mykonos, Mustique — Islands",
    enabled: true,
  },
  {
    id: 61,
    section: "06-mediterranean-islands",
    slotKey: "mykonos-staircase",
    filename: "mykonos-staircase.jpg",
    title: "Cycladic stair",
    aspect: "3:4",
    src: "/brand/06-mediterranean-islands/mykonos-staircase.jpg",
    alt: "Cycladic stair — Ibiza, Mykonos, Mustique — Islands",
    enabled: true,
  },
  {
    id: 62,
    section: "06-mediterranean-islands",
    slotKey: "ibiza-linen-curtain",
    filename: "ibiza-linen-curtain.jpg",
    title: "Linen curtain, breath of wind",
    aspect: "1:1",
    src: "/brand/06-mediterranean-islands/ibiza-linen-curtain.jpg",
    alt: "Linen curtain, breath of wind — Ibiza, Mykonos, Mustique — Islands",
    enabled: true,
  },
  {
    id: 63,
    section: "06-mediterranean-islands",
    slotKey: "mustique-veranda",
    filename: "mustique-veranda.jpg",
    title: "Mustique veranda, 17:00",
    aspect: "16:9",
    src: "/brand/06-mediterranean-islands/mustique-veranda.jpg",
    alt: "Mustique veranda, 17:00 — Ibiza, Mykonos, Mustique — Islands",
    enabled: true,
  },
  {
    id: 64,
    section: "06-mediterranean-islands",
    slotKey: "island-kitchen-stone",
    filename: "island-kitchen-stone.jpg",
    title: "Island kitchen, stone",
    aspect: "4:5",
    src: "/brand/06-mediterranean-islands/island-kitchen-stone.jpg",
    alt: "Island kitchen, stone — Ibiza, Mykonos, Mustique — Islands",
    enabled: true,
  },
  {
    id: 65,
    section: "06-mediterranean-islands",
    slotKey: "ibiza-bougainvillea-restrained",
    filename: "ibiza-bougainvillea-restrained.jpg",
    title: "Bougainvillea, restrained",
    aspect: "1:1",
    src: "/brand/06-mediterranean-islands/ibiza-bougainvillea-restrained.jpg",
    alt: "Bougainvillea, restrained — Ibiza, Mykonos, Mustique — Islands",
    enabled: true,
  },
  {
    id: 66,
    section: "06-mediterranean-islands",
    slotKey: "mykonos-jetty",
    filename: "mykonos-jetty.jpg",
    title: "Mykonos jetty, stillness",
    aspect: "21:9",
    src: "/brand/06-mediterranean-islands/mykonos-jetty.jpg",
    alt: "Mykonos jetty, stillness — Ibiza, Mykonos, Mustique — Islands",
    enabled: true,
  },
  {
    id: 67,
    section: "06-mediterranean-islands",
    slotKey: "mustique-hand-railing",
    filename: "mustique-hand-railing.jpg",
    title: "Hand on railing, salt air",
    aspect: "1:1",
    src: "/brand/06-mediterranean-islands/mustique-hand-railing.jpg",
    alt: "Hand on railing, salt air — Ibiza, Mykonos, Mustique — Islands",
    enabled: true,
  },
  {
    id: 68,
    section: "06-mediterranean-islands",
    slotKey: "mediterranean-pool-stone",
    filename: "mediterranean-pool-stone.jpg",
    title: "Stone pool, still",
    aspect: "16:9",
    src: "/brand/06-mediterranean-islands/mediterranean-pool-stone.jpg",
    alt: "Stone pool, still — Ibiza, Mykonos, Mustique — Islands",
    enabled: true,
  },
  {
    id: 69,
    section: "06-mediterranean-islands",
    slotKey: "ibiza-hilltop-olive",
    filename: "ibiza-hilltop-olive.jpg",
    title: "Olive grove, Ibiza",
    aspect: "3:4",
    src: "/brand/06-mediterranean-islands/ibiza-hilltop-olive.jpg",
    alt: "Olive grove, Ibiza — Ibiza, Mykonos, Mustique — Islands",
    enabled: true,
  },
  {
    id: 70,
    section: "06-mediterranean-islands",
    slotKey: "mykonos-evening-candle",
    filename: "mykonos-evening-candle.jpg",
    title: "Cycladic candle, 19:30",
    aspect: "1:1",
    src: "/brand/06-mediterranean-islands/mykonos-evening-candle.jpg",
    alt: "Cycladic candle, 19:30 — Ibiza, Mykonos, Mustique — Islands",
    enabled: true,
  },
  {
    id: 71,
    section: "06-mediterranean-islands",
    slotKey: "island-garden-stone",
    filename: "island-garden-stone.jpg",
    title: "Garden stone, morning",
    aspect: "16:9",
    src: "/brand/06-mediterranean-islands/island-garden-stone.jpg",
    alt: "Garden stone, morning — Ibiza, Mykonos, Mustique — Islands",
    enabled: true,
  },
  {
    id: 72,
    section: "06-mediterranean-islands",
    slotKey: "mustique-hammock-detail",
    filename: "mustique-hammock-detail.jpg",
    title: "Hammock detail, late light",
    aspect: "1:1",
    src: "/brand/06-mediterranean-islands/mustique-hammock-detail.jpg",
    alt: "Hammock detail, late light — Ibiza, Mykonos, Mustique — Islands",
    enabled: true,
  },
  // ─── §7 Provence and European Countryside ─────────────────────────────
  {
    id: 73,
    section: "07-provence-countryside",
    slotKey: "provence-farmhouse",
    filename: "provence-farmhouse.jpg",
    title: "Provence farmhouse, 08:00",
    aspect: "4:5",
    src: "/brand/07-provence-countryside/provence-farmhouse.jpg",
    alt: "Provence farmhouse, 08:00 — Provence and European Countryside",
    enabled: true,
  },
  {
    id: 74,
    section: "07-provence-countryside",
    slotKey: "provence-lavender-restrained",
    filename: "provence-lavender-restrained.jpg",
    title: "Lavender field, restrained",
    aspect: "16:9",
    src: "/brand/07-provence-countryside/provence-lavender-restrained.jpg",
    alt: "Lavender field, restrained — Provence and European Countryside",
    enabled: true,
  },
  {
    id: 75,
    section: "07-provence-countryside",
    slotKey: "provence-kitchen-terracotta",
    filename: "provence-kitchen-terracotta.jpg",
    title: "Farmhouse kitchen, quiet",
    aspect: "4:5",
    src: "/brand/07-provence-countryside/provence-kitchen-terracotta.jpg",
    alt: "Farmhouse kitchen, quiet — Provence and European Countryside",
    enabled: true,
  },
  {
    id: 76,
    section: "07-provence-countryside",
    slotKey: "tuscany-villa-loggia",
    filename: "tuscany-villa-loggia.jpg",
    title: "Tuscan loggia",
    aspect: "16:9",
    src: "/brand/07-provence-countryside/tuscany-villa-loggia.jpg",
    alt: "Tuscan loggia — Provence and European Countryside",
    enabled: true,
  },
  {
    id: 77,
    section: "07-provence-countryside",
    slotKey: "provence-garden-path",
    filename: "provence-garden-path.jpg",
    title: "Garden path, afternoon",
    aspect: "3:4",
    src: "/brand/07-provence-countryside/provence-garden-path.jpg",
    alt: "Garden path, afternoon — Provence and European Countryside",
    enabled: true,
  },
  {
    id: 78,
    section: "07-provence-countryside",
    slotKey: "tuscan-window-sill",
    filename: "tuscan-window-sill.jpg",
    title: "Tuscan window, cool light",
    aspect: "1:1",
    src: "/brand/07-provence-countryside/tuscan-window-sill.jpg",
    alt: "Tuscan window, cool light — Provence and European Countryside",
    enabled: true,
  },
  {
    id: 79,
    section: "07-provence-countryside",
    slotKey: "countryside-road",
    filename: "countryside-road.jpg",
    title: "Empty country road",
    aspect: "21:9",
    src: "/brand/07-provence-countryside/countryside-road.jpg",
    alt: "Empty country road — Provence and European Countryside",
    enabled: true,
  },
  {
    id: 80,
    section: "07-provence-countryside",
    slotKey: "provence-vineyard-morning",
    filename: "provence-vineyard-morning.jpg",
    title: "Vineyard morning",
    aspect: "16:9",
    src: "/brand/07-provence-countryside/provence-vineyard-morning.jpg",
    alt: "Vineyard morning — Provence and European Countryside",
    enabled: true,
  },
  {
    id: 81,
    section: "07-provence-countryside",
    slotKey: "provence-outdoor-bath",
    filename: "provence-outdoor-bath.jpg",
    title: "Outdoor tub, courtyard",
    aspect: "4:5",
    src: "/brand/07-provence-countryside/provence-outdoor-bath.jpg",
    alt: "Outdoor tub, courtyard — Provence and European Countryside",
    enabled: true,
  },
  {
    id: 82,
    section: "07-provence-countryside",
    slotKey: "countryside-oak-shadow",
    filename: "countryside-oak-shadow.jpg",
    title: "Single oak, shadow long",
    aspect: "16:9",
    src: "/brand/07-provence-countryside/countryside-oak-shadow.jpg",
    alt: "Single oak, shadow long — Provence and European Countryside",
    enabled: true,
  },
  // ─── §8 Caribbean and Transatlantic ─────────────────────────────
  {
    id: 83,
    section: "08-caribbean-transatlantic",
    slotKey: "caribbean-veranda-18h",
    filename: "caribbean-veranda-18h.jpg",
    title: "Caribbean veranda, 18:00",
    aspect: "16:9",
    src: "/brand/08-caribbean-transatlantic/caribbean-veranda-18h.jpg",
    alt: "Caribbean veranda, 18:00 — Caribbean and Transatlantic",
    enabled: true,
  },
  {
    id: 84,
    section: "08-caribbean-transatlantic",
    slotKey: "nyc-pied-a-terre",
    filename: "nyc-pied-a-terre.jpg",
    title: "New York pied-à-terre, morning",
    aspect: "4:5",
    src: "/brand/08-caribbean-transatlantic/nyc-pied-a-terre.jpg",
    alt: "New York pied-à-terre, morning — Caribbean and Transatlantic",
    enabled: true,
  },
  {
    id: 85,
    section: "08-caribbean-transatlantic",
    slotKey: "bahamas-dock",
    filename: "bahamas-dock.jpg",
    title: "Quiet dock, Bahamas",
    aspect: "21:9",
    src: "/brand/08-caribbean-transatlantic/bahamas-dock.jpg",
    alt: "Quiet dock, Bahamas — Caribbean and Transatlantic",
    enabled: true,
  },
  {
    id: 86,
    section: "08-caribbean-transatlantic",
    slotKey: "caribbean-house-doorway",
    filename: "caribbean-house-doorway.jpg",
    title: "House doorway, dusk",
    aspect: "3:4",
    src: "/brand/08-caribbean-transatlantic/caribbean-house-doorway.jpg",
    alt: "House doorway, dusk — Caribbean and Transatlantic",
    enabled: true,
  },
  {
    id: 87,
    section: "08-caribbean-transatlantic",
    slotKey: "mustique-interior",
    filename: "mustique-interior.jpg",
    title: "Mustique interior, cool late",
    aspect: "4:5",
    src: "/brand/08-caribbean-transatlantic/mustique-interior.jpg",
    alt: "Mustique interior, cool late — Caribbean and Transatlantic",
    enabled: true,
  },
  {
    id: 88,
    section: "08-caribbean-transatlantic",
    slotKey: "barbados-garden",
    filename: "barbados-garden.jpg",
    title: "Walled garden, morning",
    aspect: "16:9",
    src: "/brand/08-caribbean-transatlantic/barbados-garden.jpg",
    alt: "Walled garden, morning — Caribbean and Transatlantic",
    enabled: true,
  },
  {
    id: 89,
    section: "08-caribbean-transatlantic",
    slotKey: "transatlantic-cruise-window",
    filename: "transatlantic-cruise-window.jpg",
    title: "Cabin window, cruise height",
    aspect: "4:5",
    src: "/brand/08-caribbean-transatlantic/transatlantic-cruise-window.jpg",
    alt: "Cabin window, cruise height — Caribbean and Transatlantic",
    enabled: true,
  },
  {
    id: 90,
    section: "08-caribbean-transatlantic",
    slotKey: "caribbean-pool-edge",
    filename: "caribbean-pool-edge.jpg",
    title: "Pool edge, dawn",
    aspect: "1:1",
    src: "/brand/08-caribbean-transatlantic/caribbean-pool-edge.jpg",
    alt: "Pool edge, dawn — Caribbean and Transatlantic",
    enabled: true,
  },
  // ─── §9 Domestic Interiors — Before and After ─────────────────────────────
  {
    id: 91,
    section: "09-domestic-interiors",
    slotKey: "interior-breakfast-tray",
    filename: "interior-breakfast-tray.jpg",
    title: "Breakfast tray at the sash",
    aspect: "4:5",
    src: "/brand/09-domestic-interiors/interior-breakfast-tray.jpg",
    alt: "Breakfast tray at the sash — Domestic Interiors — Before and After",
    enabled: true,
  },
  {
    id: 92,
    section: "09-domestic-interiors",
    slotKey: "interior-dressing-room",
    filename: "interior-dressing-room.jpg",
    title: "Dressing room, before",
    aspect: "4:5",
    src: "/brand/09-domestic-interiors/interior-dressing-room.jpg",
    alt: "Dressing room, before — Domestic Interiors — Before and After",
    enabled: true,
  },
  {
    id: 93,
    section: "09-domestic-interiors",
    slotKey: "interior-sitting-afternoon",
    filename: "interior-sitting-afternoon.jpg",
    title: "Sitting room, 15:30",
    aspect: "4:5",
    src: "/brand/09-domestic-interiors/interior-sitting-afternoon.jpg",
    alt: "Sitting room, 15:30 — Domestic Interiors — Before and After",
    enabled: true,
  },
  {
    id: 94,
    section: "09-domestic-interiors",
    slotKey: "interior-study-lamplit",
    filename: "interior-study-lamplit.jpg",
    title: "Study, 19:00",
    aspect: "1:1",
    src: "/brand/09-domestic-interiors/interior-study-lamplit.jpg",
    alt: "Study, 19:00 — Domestic Interiors — Before and After",
    enabled: true,
  },
  {
    id: 95,
    section: "09-domestic-interiors",
    slotKey: "interior-bedroom-first-light",
    filename: "interior-bedroom-first-light.jpg",
    title: "Bedroom, first light",
    aspect: "16:9",
    src: "/brand/09-domestic-interiors/interior-bedroom-first-light.jpg",
    alt: "Bedroom, first light — Domestic Interiors — Before and After",
    enabled: true,
  },
  {
    id: 96,
    section: "09-domestic-interiors",
    slotKey: "interior-bathroom-morning",
    filename: "interior-bathroom-morning.jpg",
    title: "Bathroom, morning",
    aspect: "4:5",
    src: "/brand/09-domestic-interiors/interior-bathroom-morning.jpg",
    alt: "Bathroom, morning — Domestic Interiors — Before and After",
    enabled: true,
  },
  {
    id: 97,
    section: "09-domestic-interiors",
    slotKey: "interior-children-room-empty",
    filename: "interior-children-room-empty.jpg",
    title: "Child\'s room, tidied",
    aspect: "4:5",
    src: "/brand/09-domestic-interiors/interior-children-room-empty.jpg",
    alt: "Child\'s room, tidied — Domestic Interiors — Before and After",
    enabled: true,
  },
  {
    id: 98,
    section: "09-domestic-interiors",
    slotKey: "interior-pet-basket",
    filename: "interior-pet-basket.jpg",
    title: "Pet basket, morning",
    aspect: "1:1",
    src: "/brand/09-domestic-interiors/interior-pet-basket.jpg",
    alt: "Pet basket, morning — Domestic Interiors — Before and After",
    enabled: true,
  },
  {
    id: 99,
    section: "09-domestic-interiors",
    slotKey: "interior-staff-space",
    filename: "interior-staff-space.jpg",
    title: "Quiet staff corridor",
    aspect: "4:5",
    src: "/brand/09-domestic-interiors/interior-staff-space.jpg",
    alt: "Quiet staff corridor — Domestic Interiors — Before and After",
    enabled: true,
  },
  {
    id: 100,
    section: "09-domestic-interiors",
    slotKey: "interior-kitchen-late",
    filename: "interior-kitchen-late.jpg",
    title: "Kitchen, late return",
    aspect: "4:5",
    src: "/brand/09-domestic-interiors/interior-kitchen-late.jpg",
    alt: "Kitchen, late return — Domestic Interiors — Before and After",
    enabled: true,
  },
  {
    id: 101,
    section: "09-domestic-interiors",
    slotKey: "interior-hall-evening-return",
    filename: "interior-hall-evening-return.jpg",
    title: "Hallway, evening return",
    aspect: "16:9",
    src: "/brand/09-domestic-interiors/interior-hall-evening-return.jpg",
    alt: "Hallway, evening return — Domestic Interiors — Before and After",
    enabled: true,
  },
  {
    id: 102,
    section: "09-domestic-interiors",
    slotKey: "interior-library-shelf",
    filename: "interior-library-shelf.jpg",
    title: "Shelf, fore-edges",
    aspect: "1:1",
    src: "/brand/09-domestic-interiors/interior-library-shelf.jpg",
    alt: "Shelf, fore-edges — Domestic Interiors — Before and After",
    enabled: true,
  },
  {
    id: 103,
    section: "09-domestic-interiors",
    slotKey: "interior-window-seat",
    filename: "interior-window-seat.jpg",
    title: "Window seat, reading",
    aspect: "4:5",
    src: "/brand/09-domestic-interiors/interior-window-seat.jpg",
    alt: "Window seat, reading — Domestic Interiors — Before and After",
    enabled: true,
  },
  {
    id: 104,
    section: "09-domestic-interiors",
    slotKey: "interior-flowers-restrained",
    filename: "interior-flowers-restrained.jpg",
    title: "Flowers, restrained",
    aspect: "1:1",
    src: "/brand/09-domestic-interiors/interior-flowers-restrained.jpg",
    alt: "Flowers, restrained — Domestic Interiors — Before and After",
    enabled: true,
  },
  {
    id: 105,
    section: "09-domestic-interiors",
    slotKey: "interior-stairs-runner",
    filename: "interior-stairs-runner.jpg",
    title: "Stairs runner, morning",
    aspect: "3:4",
    src: "/brand/09-domestic-interiors/interior-stairs-runner.jpg",
    alt: "Stairs runner, morning — Domestic Interiors — Before and After",
    enabled: true,
  },
  // ─── §10 Cabin Stills — Interior of the Aircraft ─────────────────────────────
  {
    id: 106,
    section: "10-cabin-stills",
    slotKey: "cabin-seat-belt-folded",
    filename: "cabin-seat-belt-folded.jpg",
    title: "Seat belt folded, ready",
    aspect: "1:1",
    src: "/brand/10-cabin-stills/cabin-seat-belt-folded.jpg",
    alt: "Seat belt folded, ready — Cabin Stills — Interior of the Aircraft",
    enabled: true,
  },
  {
    id: 107,
    section: "10-cabin-stills",
    slotKey: "cabin-window-soft-cloud",
    filename: "cabin-window-soft-cloud.jpg",
    title: "Oval window, cloud",
    aspect: "4:5",
    src: "/brand/10-cabin-stills/cabin-window-soft-cloud.jpg",
    alt: "Oval window, cloud — Cabin Stills — Interior of the Aircraft",
    enabled: true,
  },
  {
    id: 108,
    section: "10-cabin-stills",
    slotKey: "cabin-galley-detail",
    filename: "cabin-galley-detail.jpg",
    title: "Galley, ready",
    aspect: "4:5",
    src: "/brand/10-cabin-stills/cabin-galley-detail.jpg",
    alt: "Galley, ready — Cabin Stills — Interior of the Aircraft",
    enabled: true,
  },
  {
    id: 109,
    section: "10-cabin-stills",
    slotKey: "cabin-throw-still",
    filename: "cabin-throw-still.jpg",
    title: "Cashmere throw in cabin",
    aspect: "1:1",
    src: "/brand/10-cabin-stills/cabin-throw-still.jpg",
    alt: "Cashmere throw in cabin — Cabin Stills — Interior of the Aircraft",
    enabled: true,
  },
  {
    id: 110,
    section: "10-cabin-stills",
    slotKey: "cabin-water-carafe",
    filename: "cabin-water-carafe.jpg",
    title: "Carafe on walnut table",
    aspect: "1:1",
    src: "/brand/10-cabin-stills/cabin-water-carafe.jpg",
    alt: "Carafe on walnut table — Cabin Stills — Interior of the Aircraft",
    enabled: true,
  },
  {
    id: 111,
    section: "10-cabin-stills",
    slotKey: "cabin-reading-lamp",
    filename: "cabin-reading-lamp.jpg",
    title: "Reading lamp, mid-flight",
    aspect: "4:5",
    src: "/brand/10-cabin-stills/cabin-reading-lamp.jpg",
    alt: "Reading lamp, mid-flight — Cabin Stills — Interior of the Aircraft",
    enabled: true,
  },
  {
    id: 112,
    section: "10-cabin-stills",
    slotKey: "cabin-stateroom-bed",
    filename: "cabin-stateroom-bed.jpg",
    title: "Stateroom, turned down",
    aspect: "16:9",
    src: "/brand/10-cabin-stills/cabin-stateroom-bed.jpg",
    alt: "Stateroom, turned down — Cabin Stills — Interior of the Aircraft",
    enabled: true,
  },
  {
    id: 113,
    section: "10-cabin-stills",
    slotKey: "cabin-bulkhead-detail",
    filename: "cabin-bulkhead-detail.jpg",
    title: "Bulkhead, walnut",
    aspect: "1:1",
    src: "/brand/10-cabin-stills/cabin-bulkhead-detail.jpg",
    alt: "Bulkhead, walnut — Cabin Stills — Interior of the Aircraft",
    enabled: true,
  },
  {
    id: 114,
    section: "10-cabin-stills",
    slotKey: "cabin-laptop-tablet",
    filename: "cabin-laptop-tablet.jpg",
    title: "Member desk, mid-flight",
    aspect: "16:9",
    src: "/brand/10-cabin-stills/cabin-laptop-tablet.jpg",
    alt: "Member desk, mid-flight — Cabin Stills — Interior of the Aircraft",
    enabled: true,
  },
  {
    id: 115,
    section: "10-cabin-stills",
    slotKey: "cabin-crew-still",
    filename: "cabin-crew-still.jpg",
    title: "Galley detail, crew-set",
    aspect: "1:1",
    src: "/brand/10-cabin-stills/cabin-crew-still.jpg",
    alt: "Galley detail, crew-set — Cabin Stills — Interior of the Aircraft",
    enabled: true,
  },
  {
    id: 116,
    section: "10-cabin-stills",
    slotKey: "cabin-pet-carrier",
    filename: "cabin-pet-carrier.jpg",
    title: "Pet carrier, tucked",
    aspect: "4:5",
    src: "/brand/10-cabin-stills/cabin-pet-carrier.jpg",
    alt: "Pet carrier, tucked — Cabin Stills — Interior of the Aircraft",
    enabled: true,
  },
  {
    id: 117,
    section: "10-cabin-stills",
    slotKey: "cabin-skis-correct-scale",
    filename: "cabin-skis-correct-scale.jpg",
    title: "Ski bag at threshold",
    aspect: "16:9",
    src: "/brand/10-cabin-stills/cabin-skis-correct-scale.jpg",
    alt: "Ski bag at threshold — Cabin Stills — Interior of the Aircraft",
    enabled: true,
  },
  {
    id: 118,
    section: "10-cabin-stills",
    slotKey: "cabin-breakfast-late",
    filename: "cabin-breakfast-late.jpg",
    title: "Mid-flight breakfast",
    aspect: "3:4",
    src: "/brand/10-cabin-stills/cabin-breakfast-late.jpg",
    alt: "Mid-flight breakfast — Cabin Stills — Interior of the Aircraft",
    enabled: true,
  },
  // ─── §11 Hands-only Vignettes and Human Fragments ─────────────────────────────
  {
    id: 119,
    section: "11-hands-and-vignettes",
    slotKey: "hand-stone-balustrade",
    filename: "hand-stone-balustrade.jpg",
    title: "Hand on stone, lake",
    aspect: "1:1",
    src: "/brand/11-hands-and-vignettes/hand-stone-balustrade.jpg",
    alt: "Hand on stone, lake — Hands-only Vignettes and Human Fragments",
    enabled: true,
  },
  {
    id: 120,
    section: "11-hands-and-vignettes",
    slotKey: "hand-brass-railing",
    filename: "hand-brass-railing.jpg",
    title: "Hand on brass rail",
    aspect: "1:1",
    src: "/brand/11-hands-and-vignettes/hand-brass-railing.jpg",
    alt: "Hand on brass rail — Hands-only Vignettes and Human Fragments",
    enabled: true,
  },
  {
    id: 121,
    section: "11-hands-and-vignettes",
    slotKey: "breath-cold-glass",
    filename: "breath-cold-glass.jpg",
    title: "Breath on glass",
    aspect: "1:1",
    src: "/brand/11-hands-and-vignettes/breath-cold-glass.jpg",
    alt: "Breath on glass — Hands-only Vignettes and Human Fragments",
    enabled: true,
  },
  {
    id: 122,
    section: "11-hands-and-vignettes",
    slotKey: "cuff-sill",
    filename: "cuff-sill.jpg",
    title: "Wool cuff on sill",
    aspect: "1:1",
    src: "/brand/11-hands-and-vignettes/cuff-sill.jpg",
    alt: "Wool cuff on sill — Hands-only Vignettes and Human Fragments",
    enabled: false, // Disabled 2026-05-05 — Michael: "decapitated hand no thanks"
  },
  {
    id: 123,
    section: "11-hands-and-vignettes",
    slotKey: "hands-folded-linen",
    filename: "hands-folded-linen.jpg",
    title: "Hands, folded linen",
    aspect: "1:1",
    src: "/brand/11-hands-and-vignettes/hands-folded-linen.jpg",
    alt: "Hands, folded linen — Hands-only Vignettes and Human Fragments",
    enabled: true,
  },
  {
    id: 124,
    section: "11-hands-and-vignettes",
    slotKey: "shoulder-receding-hall",
    filename: "shoulder-receding-hall.jpg",
    title: "Shoulder receding",
    aspect: "16:9",
    src: "/brand/11-hands-and-vignettes/shoulder-receding-hall.jpg",
    alt: "Shoulder receding — Hands-only Vignettes and Human Fragments",
    enabled: true,
  },
  {
    id: 125,
    section: "11-hands-and-vignettes",
    slotKey: "hand-at-car-door",
    filename: "hand-at-car-door.jpg",
    title: "Hand at the car door",
    aspect: "16:9",
    src: "/brand/11-hands-and-vignettes/hand-at-car-door.jpg",
    alt: "Hand at the car door — Hands-only Vignettes and Human Fragments",
    enabled: true,
  },
  {
    id: 126,
    section: "11-hands-and-vignettes",
    slotKey: "profile-out-of-focus",
    filename: "profile-out-of-focus.jpg",
    title: "Profile, deeply out of focus",
    aspect: "4:5",
    src: "/brand/11-hands-and-vignettes/profile-out-of-focus.jpg",
    alt: "Profile, deeply out of focus — Hands-only Vignettes and Human Fragments",
    enabled: true,
  },
  {
    id: 127,
    section: "11-hands-and-vignettes",
    slotKey: "reflected-silhouette",
    filename: "reflected-silhouette.jpg",
    title: "Silhouette in glass",
    aspect: "4:5",
    src: "/brand/11-hands-and-vignettes/reflected-silhouette.jpg",
    alt: "Silhouette in glass — Hands-only Vignettes and Human Fragments",
    enabled: true,
  },
  {
    id: 128,
    section: "11-hands-and-vignettes",
    slotKey: "hand-harbour-rope",
    filename: "hand-harbour-rope.jpg",
    title: "Hand on mooring rope",
    aspect: "1:1",
    src: "/brand/11-hands-and-vignettes/hand-harbour-rope.jpg",
    alt: "Hand on mooring rope — Hands-only Vignettes and Human Fragments",
    enabled: true,
  },
  {
    id: 129,
    section: "11-hands-and-vignettes",
    slotKey: "forearm-railing-alpine",
    filename: "forearm-railing-alpine.jpg",
    title: "Forearm, alpine rail",
    aspect: "1:1",
    src: "/brand/11-hands-and-vignettes/forearm-railing-alpine.jpg",
    alt: "Forearm, alpine rail — Hands-only Vignettes and Human Fragments",
    enabled: true,
  },
  {
    id: 130,
    section: "11-hands-and-vignettes",
    slotKey: "hand-porcelain-cup",
    filename: "hand-porcelain-cup.jpg",
    title: "Hand, porcelain cup",
    aspect: "1:1",
    src: "/brand/11-hands-and-vignettes/hand-porcelain-cup.jpg",
    alt: "Hand, porcelain cup — Hands-only Vignettes and Human Fragments",
    enabled: false, // Disabled 2026-05-05 — Michael: "completely senseless unless we're selling prosthesis"
  },
  {
    id: 131,
    section: "11-hands-and-vignettes",
    slotKey: "back-of-head-car",
    filename: "back-of-head-car.jpg",
    title: "Back of head, rear seat",
    aspect: "16:9",
    src: "/brand/11-hands-and-vignettes/back-of-head-car.jpg",
    alt: "Back of head, rear seat — Hands-only Vignettes and Human Fragments",
    enabled: true,
  },
  {
    id: 132,
    section: "11-hands-and-vignettes",
    slotKey: "hand-alpine-glove",
    filename: "hand-alpine-glove.jpg",
    title: "Glove on timber",
    aspect: "1:1",
    src: "/brand/11-hands-and-vignettes/hand-alpine-glove.jpg",
    alt: "Glove on timber — Hands-only Vignettes and Human Fragments",
    enabled: true,
  },
  // ─── §12 Textures, Ambient Light and Arrivals ─────────────────────────────
  {
    id: 133,
    section: "12-textures-ambient-arrivals",
    slotKey: "texture-linen-weave",
    filename: "texture-linen-weave.jpg",
    title: "Linen weave, close",
    aspect: "1:1",
    src: "/brand/12-textures-ambient-arrivals/texture-linen-weave.jpg",
    alt: "Linen weave, close — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 134,
    section: "12-textures-ambient-arrivals",
    slotKey: "texture-walnut-grain",
    filename: "texture-walnut-grain.jpg",
    title: "Walnut grain, lamplit",
    aspect: "1:1",
    src: "/brand/12-textures-ambient-arrivals/texture-walnut-grain.jpg",
    alt: "Walnut grain, lamplit — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 135,
    section: "12-textures-ambient-arrivals",
    slotKey: "texture-brass-worn",
    filename: "texture-brass-worn.jpg",
    title: "Brass handle, worn",
    aspect: "1:1",
    src: "/brand/12-textures-ambient-arrivals/texture-brass-worn.jpg",
    alt: "Brass handle, worn — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 136,
    section: "12-textures-ambient-arrivals",
    slotKey: "texture-oak-floor",
    filename: "texture-oak-floor.jpg",
    title: "Wide-board oak floor",
    aspect: "3:4",
    src: "/brand/12-textures-ambient-arrivals/texture-oak-floor.jpg",
    alt: "Wide-board oak floor — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 137,
    section: "12-textures-ambient-arrivals",
    slotKey: "ambient-alpine-first-light",
    filename: "ambient-alpine-first-light.jpg",
    title: "Alpine first light",
    aspect: "21:9",
    src: "/brand/12-textures-ambient-arrivals/ambient-alpine-first-light.jpg",
    alt: "Alpine first light — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 138,
    section: "12-textures-ambient-arrivals",
    slotKey: "ambient-mediterranean-late",
    filename: "ambient-mediterranean-late.jpg",
    title: "Mediterranean late sun",
    aspect: "21:9",
    src: "/brand/12-textures-ambient-arrivals/ambient-mediterranean-late.jpg",
    alt: "Mediterranean late sun — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 139,
    section: "12-textures-ambient-arrivals",
    slotKey: "ambient-london-overcast",
    filename: "ambient-london-overcast.jpg",
    title: "London overcast, 07:30",
    aspect: "16:9",
    src: "/brand/12-textures-ambient-arrivals/ambient-london-overcast.jpg",
    alt: "London overcast, 07:30 — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 140,
    section: "12-textures-ambient-arrivals",
    slotKey: "ambient-lugano-dusk",
    filename: "ambient-lugano-dusk.jpg",
    title: "Lugano quay at dusk",
    aspect: "16:9",
    src: "/brand/12-textures-ambient-arrivals/ambient-lugano-dusk.jpg",
    alt: "Lugano quay at dusk — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 141,
    section: "12-textures-ambient-arrivals",
    slotKey: "arrange-car-waiting",
    filename: "arrange-car-waiting.jpg",
    title: "Car waiting, threshold",
    aspect: "16:9",
    src: "/brand/12-textures-ambient-arrivals/arrange-car-waiting.jpg",
    alt: "Car waiting, threshold — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 142,
    section: "12-textures-ambient-arrivals",
    slotKey: "arrange-florist-dawn",
    filename: "arrange-florist-dawn.jpg",
    title: "Florist delivery, 07:00",
    aspect: "1:1",
    src: "/brand/12-textures-ambient-arrivals/arrange-florist-dawn.jpg",
    alt: "Florist delivery, 07:00 — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 143,
    section: "12-textures-ambient-arrivals",
    slotKey: "arrange-garment-bag",
    filename: "arrange-garment-bag.jpg",
    title: "Garment bag, hall chair",
    aspect: "4:5",
    src: "/brand/12-textures-ambient-arrivals/arrange-garment-bag.jpg",
    alt: "Garment bag, hall chair — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 144,
    section: "12-textures-ambient-arrivals",
    slotKey: "arrange-concierge-note",
    filename: "arrange-concierge-note.jpg",
    title: "Concierge note, folded",
    aspect: "1:1",
    src: "/brand/12-textures-ambient-arrivals/arrange-concierge-note.jpg",
    alt: "Concierge note, folded — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 145,
    section: "12-textures-ambient-arrivals",
    slotKey: "arrival-london-sash",
    filename: "arrival-london-sash.jpg",
    title: "Arrival, sash rain",
    aspect: "3:4",
    src: "/brand/12-textures-ambient-arrivals/arrival-london-sash.jpg",
    alt: "Arrival, sash rain — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 146,
    section: "12-textures-ambient-arrivals",
    slotKey: "arrival-alpine-porch",
    filename: "arrival-alpine-porch.jpg",
    title: "Arrival, alpine porch",
    aspect: "16:9",
    src: "/brand/12-textures-ambient-arrivals/arrival-alpine-porch.jpg",
    alt: "Arrival, alpine porch — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 147,
    section: "12-textures-ambient-arrivals",
    slotKey: "arrival-island-door",
    filename: "arrival-island-door.jpg",
    title: "Arrival, island door",
    aspect: "4:5",
    src: "/brand/12-textures-ambient-arrivals/arrival-island-door.jpg",
    alt: "Arrival, island door — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 148,
    section: "12-textures-ambient-arrivals",
    slotKey: "ambient-mist-on-lake",
    filename: "ambient-mist-on-lake.jpg",
    title: "Mist on water, 06:45",
    aspect: "21:9",
    src: "/brand/12-textures-ambient-arrivals/ambient-mist-on-lake.jpg",
    alt: "Mist on water, 06:45 — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 149,
    section: "12-textures-ambient-arrivals",
    slotKey: "ambient-candle-evening",
    filename: "ambient-candle-evening.jpg",
    title: "Candle, evening interior",
    aspect: "1:1",
    src: "/brand/12-textures-ambient-arrivals/ambient-candle-evening.jpg",
    alt: "Candle, evening interior — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  {
    id: 150,
    section: "12-textures-ambient-arrivals",
    slotKey: "ambient-cabin-empty-ready",
    filename: "ambient-cabin-empty-ready.jpg",
    title: "Cabin ready, night return",
    aspect: "21:9",
    src: "/brand/12-textures-ambient-arrivals/ambient-cabin-empty-ready.jpg",
    alt: "Cabin ready, night return — Textures, Ambient Light and Arrivals",
    enabled: true,
  },
  // ─── §13 Milan — the English-speaker city ─────────────────────────────
  {
    id: 151,
    section: "13-milan-english-speaker-city",
    slotKey: "milan-linate-fbo-first-light",
    filename: "milan-linate-fbo-first-light.jpg",
    title: "Linate FBO, first light",
    aspect: "21:9",
    src: "/brand/13-milan-english-speaker-city/milan-linate-fbo-first-light.jpg",
    alt: "Linate FBO, first light — Milan — the English-speaker city",
    enabled: true,
  },
  {
    id: 152,
    section: "13-milan-english-speaker-city",
    slotKey: "milan-brera-arcade-morning",
    filename: "milan-brera-arcade-morning.jpg",
    title: "Brera arcade, before the city",
    aspect: "16:9",
    src: "/brand/13-milan-english-speaker-city/milan-brera-arcade-morning.jpg",
    alt: "Brera arcade, before the city — Milan — the English-speaker city",
    enabled: true,
  },
  {
    id: 153,
    section: "13-milan-english-speaker-city",
    slotKey: "milan-palazzo-courtyard",
    filename: "milan-palazzo-courtyard.jpg",
    title: "Palazzo courtyard, sycamore shadow",
    aspect: "3:4",
    src: "/brand/13-milan-english-speaker-city/milan-palazzo-courtyard.jpg",
    alt: "Palazzo courtyard, sycamore shadow — Milan — the English-speaker city",
    enabled: true,
  },
  {
    id: 154,
    section: "13-milan-english-speaker-city",
    slotKey: "milan-lake-como-villa-terrace",
    filename: "milan-lake-como-villa-terrace.jpg",
    title: "Lake Como villa terrace, 06:45",
    aspect: "4:5",
    src: "/brand/13-milan-english-speaker-city/milan-lake-como-villa-terrace.jpg",
    alt: "Lake Como villa terrace, 06:45 — Milan — the English-speaker city",
    enabled: true,
  },
  {
    id: 155,
    section: "13-milan-english-speaker-city",
    slotKey: "milan-quadrilatero-dusk",
    filename: "milan-quadrilatero-dusk.jpg",
    title: "Quadrilatero d\'Oro, late autumn dusk",
    aspect: "16:9",
    src: "/brand/13-milan-english-speaker-city/milan-quadrilatero-dusk.jpg",
    alt: "Quadrilatero d\'Oro, late autumn dusk — Milan — the English-speaker city",
    enabled: true,
  },
  {
    id: 156,
    section: "13-milan-english-speaker-city",
    slotKey: "milan-navigli-first-light",
    filename: "milan-navigli-first-light.jpg",
    title: "Navigli reflection, first light",
    aspect: "21:9",
    src: "/brand/13-milan-english-speaker-city/milan-navigli-first-light.jpg",
    alt: "Navigli reflection, first light — Milan — the English-speaker city",
    enabled: true,
  },
  {
    id: 157,
    section: "13-milan-english-speaker-city",
    slotKey: "milan-english-kitchen-italian-window",
    filename: "milan-english-kitchen-italian-window.jpg",
    title: "English kitchen, Italian shutters beyond",
    aspect: "4:5",
    src: "/brand/13-milan-english-speaker-city/milan-english-kitchen-italian-window.jpg",
    alt: "English kitchen, Italian shutters beyond — Milan — the English-speaker city",
    enabled: true,
  },
  {
    id: 158,
    section: "13-milan-english-speaker-city",
    slotKey: "milan-mayfair-coded-study",
    filename: "milan-mayfair-coded-study.jpg",
    title: "Mayfair-coded study with Linate haze",
    aspect: "3:4",
    src: "/brand/13-milan-english-speaker-city/milan-mayfair-coded-study.jpg",
    alt: "Mayfair-coded study with Linate haze — Milan — the English-speaker city",
    enabled: true,
  },
  {
    id: 159,
    section: "13-milan-english-speaker-city",
    slotKey: "milan-tea-on-marble",
    filename: "milan-tea-on-marble.jpg",
    title: "Tea things on Milan marble, 08:15",
    aspect: "1:1",
    src: "/brand/13-milan-english-speaker-city/milan-tea-on-marble.jpg",
    alt: "Tea things on Milan marble, 08:15 — Milan — the English-speaker city",
    enabled: true,
  },
  {
    id: 160,
    section: "13-milan-english-speaker-city",
    slotKey: "milan-walnut-library-como-view",
    filename: "milan-walnut-library-como-view.jpg",
    title: "Walnut library, Como view at 16:00",
    aspect: "16:9",
    src: "/brand/13-milan-english-speaker-city/milan-walnut-library-como-view.jpg",
    alt: "Walnut library, Como view at 16:00 — Milan — the English-speaker city",
    enabled: true,
  },
  {
    id: 161,
    section: "13-milan-english-speaker-city",
    slotKey: "milan-dressing-room-italian-light",
    filename: "milan-dressing-room-italian-light.jpg",
    title: "Dressing room, sash window, Milan",
    aspect: "4:5",
    src: "/brand/13-milan-english-speaker-city/milan-dressing-room-italian-light.jpg",
    alt: "Dressing room, sash window, Milan — Milan — the English-speaker city",
    enabled: true,
  },
  {
    id: 162,
    section: "13-milan-english-speaker-city",
    slotKey: "milan-como-weekend-kitchen",
    filename: "milan-como-weekend-kitchen.jpg",
    title: "Como weekend kitchen — could be the Cotswolds",
    aspect: "4:5",
    src: "/brand/13-milan-english-speaker-city/milan-como-weekend-kitchen.jpg",
    alt: "Como weekend kitchen — could be the Cotswolds — Milan — the English-speaker city",
    enabled: true,
  },
];

/** Stable keys components import — never reference raw ids.
 *
 * CURATION RULE — no visual overlap with u-calm-concierge.
 *
 * Some members will visit u-calm-concierge first and arrive at
 * u-calm-aviation having already seen its 47-image library. If aviation
 * repeats concierge scenes (London hallway with camel coat, Lugano-from-
 * Paradiso, Ticinese kitchen, Saanen hearth, Paradiso threshold return)
 * the journey from concierge → aviation goes flat. The narrative must
 * progress: aviation's job is to take the member into the air, into the
 * cabin, into Milan (which concierge does not have), and into FBO /
 * destination registers concierge does not photograph.
 *
 * The picks below therefore lean almost entirely on:
 *   • §10 Cabin Stills (IDs 106-118) — concierge has zero cabin shots
 *   • §13 Milan (IDs 151-162) — concierge has zero Milan
 *   • §1 aviation-coded heroes (especially #3 Aviation arranged, #4 Lake
 *     Lugano first-light-hand, #8 Cabin window cloud, #10 Navigation macro)
 *   • Three Cities axis (Lugano-different-angle / Milan / London-as-FBO)
 *
 * Avoided:
 *   • Aviation #1, #11, #15-18 (London domestic — concierge owns this register)
 *   • Aviation #25, #28, #34 (Ticinese / Lugano-Paradiso — concierge owns)
 *   • Aviation #91, #95 (generic domestic interiors — concierge has plenty)
 *   • Aviation #22 (London evening return — too close to concierge #49)
 */

/** Page heroes — full-bleed photo behind each page's hero band.
 *
 *  Re-allocated 2026-05-05 after first-draft review. Each slot reasoned
 *  against the actual page copy and Raf's must-keep signals. Replaced
 *  picks: services (galley→dressing room), destinations (ski-bag→Monaco
 *  balcony), contact (nav-abstract→linen curtain).
 */
export const PAGE_HEROES = {
  home:           3,  // §1 Aviation, arranged — empty cabin at dawn. Title IS the brand promise. Raf flagged.
  services:      14,  // §2 Dressing room before departure — Raf must-keep. The moment OF service rendering: prepared for, before the aircraft. Replaces #108 galley.
  destinations:   6,  // §1 Monaco balcony, 17:30 — Raf flagged TWICE. Quintessential destination evocation: place, coast, golden hour. Replaces #117 ski-bag.
  about:        152,  // §13 Brera arcade, before the city — Raf must-keep. "The house and the city as one." Establishment register.
  contact:       62,  // §6 Linen curtain, breath of wind — Raf must-keep. Calm + invitation; reads "open conversation." Replaces #10 nav-abstract.
  serviceDetail: 107, // §10 Oval window, cloud — fallback only; not actively consumed (services-data maps each service to a SERVICES_SCENES key).
} as const;

/** The Three Cities — Lugano · Milan · London visual triad on Home.
 *  Each city picks an atmospheric place-evocation rather than an
 *  operational airport — aviation register lives elsewhere on the page. */
export const THREE_CITIES = {
  lugano:                4,   // §1 Lake Lugano first light w/ hand on stone — Raf double-flag.
  milan:               156,   // §13 Navigli reflection, first light — Raf must-keep. Cinematic canal-at-dawn Milan; replaces #151 Linate FBO (a building/airport reads bland for a city card).
  london:               12,   // §2 Mews doorway, rain — Raf must-keep. Atmospheric London mews threshold; replaces #19 Farnborough (just a plane on tarmac was too operational for a city card). #19 + #151 stay in the library for future use elsewhere.
  milanEnglishSpeaker: 157,   // §13 English kitchen + Italian shutters — strategic visual rhyme
} as const;

/** Home editorial — paired-image continuity bands on the Home page.
 *
 *  Index §2 ("The concierge who arranges your week, now arranges the
 *  aircraft.") renders BOTH `one` and `two` stacked in the left column
 *  so the photograph mirrors the transition the copy describes:
 *  residence → cabin, same calm tray-and-porcelain register on both
 *  sides of the move. Updated 2026-05-05 after live-site review:
 *  showing only the residence half left readers asking where the
 *  aviation half went.
 */
export const HOME_EDITORIAL = {
  one:  91,   // §9 Breakfast tray at the sash — appetising residence breakfast at 07:45 (croissant + berries + honey + coffee). Regenerated 2026-05-05 with the breakfast palette exception so the tray actually reads as appetising; previously felt clinical. Pairs with #118.
  two: 118,   // §10 Mid-flight breakfast on the walnut cabin table — the SAME breakfast, transposed to cruise altitude. Regenerated 2026-05-05 with the same palette exception + explicit composition rhyme with #91. Replaces #110 carafe (a water glass didn't carry the emotional weight of a real residence→cabin transition; the rhyme of two breakfasts does).
} as const;

/** Service-section imagery — keys match the imageSlot field on Service entries.
 *
 *  Re-allocated 2026-05-05. `protection` slot added so executive-protection
 *  no longer shares `corporate` with group-charter. `phone` (on-demand) and
 *  `corporate` (group charter) re-pointed to fit-for-purpose images.
 */
export const SERVICES_SCENES = {
  aviation:    114,  // Bespoke charter. §10 Member desk mid-flight — on-board service rendered. Direct match.
  ground:       17,  // Destination management. §2 Car at kerb — direct match for "cars at both ends."
  relocations: 117,  // (Reserved — no service maps to this slot today.) §10 Ski bag at threshold — Raf must-keep.
  corporate:   141,  // Group charter. §12 Car waiting, threshold — convoy/multi-vehicle arrival fits "fifteen people, one itinerary." Replaces #106 (seat-belt = solo not group).
  protection:  125,  // Executive protection. §11 Hand at the car door — discreet close-protection signal without theatrical security imagery. NEW slot, split out of `corporate` 2026-05-05.
  travelEvents: 25,  // (Reserved.) §3 Lugano villa terrace at dawn — Raf must-keep. Alpine/lake event-coded.
  phone:       150,  // On-demand. §12 Cabin ready, night return — "we are already moving while the conversation is on the line." Replaces #133 (linen texture too quiet for urgent service).
  coolCalm:    160,  // Membership. §13 Walnut library, Como view — member residence, lived-in calm.
} as const;

/** About-page editorial scenes. */
export const ABOUT_SCENES = {
  parcoCiani:     4,   // (Reserved — not consumed in About today.) §1 Lake Lugano first light — origin-coded.
  founding2013:  27,   // §3 Lake jetty, morning mist — Raf must-keep. Lugano + dawn + slow-time = perfect fit for "founded in Lugano 2013, quietly over years." Replaces #156 (Navigli is Milan, not founding-coded).
  calmAcronym:  133,   // §12 textures-linen-weave — vignette accent (80×80 frame). Linen = continuity texture beside "the same hand, from breakfast to wheels-up."
  household:    158,   // §13 Mayfair-coded study with Linate haze — Raf must-keep. Single most apt image in the library for "Aviation, inside U-CALM" (a member's study with aviation visible through the window). Replaces #160 (now reserved for Membership service).
  team:         127,   // §11 Reflected silhouette in glass — Michael's verdict: "like it". Team rendered indirectly without faces. Replaces #129 (Michael flagged "weird hand placement, where is the body?" 2026-05-05).
} as const;

export const CONTACT_EDITORIAL = {
  one: 137,   // §12 Alpine first light — Raf must-keep. Calm + listening register; reserved/typed for when Contact gains an editorial band. Replaces #108 galley (microwave aesthetic was wrong for contact).
} as const;

/** Seasonal / textural bank — used for footer textures, destinations gallery,
 *  closing bands. Picks lean on cabin-stills, Milan, and aviation-specific
 *  scenes throughout (no overlap with concierge's seasonal bank). */
export const SEASONAL_BANK = {
  springMagnolia:      71,   // §6 Garden stone, morning — Raf must-keep. Mediterranean spring (concierge owns Lugano-magnolia register).
  summerBlueHour:     138,   // §12 Mediterranean late sun — texture. Replaces #49 (Monte Carlo balcony) so Monaco isn't repeated alongside #6 PAGE_HEROES.destinations and #49 destinations card.
  autumnCatChair:     134,   // §12 Walnut grain, lamplit — autumn texture. Replaces #133 (linen weave, now used as ABOUT_SCENES.calmAcronym).
  winterHearth:         5,   // §1 Chalet morning, Gstaad — Footer texture band. Warm, calm, hearth-coded.
  christmasTable:     154,   // §13 Lake Como villa terrace, breakfast laid — Raf must-keep. Reserved for Christmas band.
  newYearFirstLight:    4,   // §1 Lake Lugano first light — Raf must-keep. Reserved for New Year band.
  backToSchool:       152,   // §13 Brera arcade morning — Raf must-keep. "Back to city" register.
  midsummerTerrace:     9,   // §1 Mustique veranda — Raf must-keep (flagged twice). Iconic midsummer; consumed in Destinations gallery + ServiceDetail editorial.
  autumnLurcherWalk:   82,   // §7 Single oak, shadow long — autumn long-shadow countryside. Replaces #73 farmhouse (less specific to "lurcher walk" register).
  disruption:         110,   // §10 Carafe on walnut cabin table — calm in disruption.
  springDinner:        45,   // §4 Morning coffee, balcony — alpine spring/early-summer.
  returningHome:      146,   // §12 Arrival, alpine porch — ambient-arrival register fits Index §10 closing copy ("the housekeeper, the dinner reservation") without straying into concierge-owned §09 domestic interiors. Replaces #112 stateroom (cabin-bed didn't match "returning home" copy).
} as const;

export function byId(id: number): BrandImage {
  const image = BRAND_IMAGES.find((entry) => entry.id === id);
  if (!image) {
    throw new Error(`No brand image found with id ${id}. Check src/brand/imagery.ts.`);
  }
  return image;
}

export function bySection(section: string): readonly BrandImage[] {
  return BRAND_IMAGES.filter((entry) => entry.section === section);
}

/**
 * Set to `true` once the U-Calm Aviation imagery has been generated
 * (via Gemini, brand-assets/scripts/generate_imagery.py — see runbook
 * IMAGERY_RUNBOOK.md) and uploaded to /public/brand/.
 *
 * 2026-05-04 — flipped to true after Raf's first-pass review. 161/162
 * generated images are now in /public/brand/<section>/. The only missing
 * one is #51 monaco-study-lamplit (library reserve, not wired to any
 * typed slot — site renders cleanly without it; regenerate later).
 *
 * Final curation pending Michael's review tonight; this is the working
 * first-draft visual.
 */
export const IMAGERY_READY = true;

export function isPlaceholder(_src: string): boolean {
  // While the library is in placeholder mode, every src is treated as
  // unfilled so <BrandImage> renders the gradient stand-in.
  return !IMAGERY_READY;
}

